name: chron
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.1+2

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.26.0
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  auto_route: ^7.8.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  local_auth: ^2.1.7
  shared_preferences: ^2.2.2
  loading_animation_widget: ^1.2.0+4
  flutter_launcher_icons: ^0.13.1
  

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/